### ISSUE TITLE
Mount EFS volume

### ISSUE THREAD

**Issue by chathsuom** [bottlerocket-os/bottlerocket-admin-container#15]
Need a way to persist some user data. Is there a way to attach an EFS volume to Admin container?

**Comment by etungsten** [comment]
If you're running the admin container as a host container in Bottlerocket, it has persistent storage under `/.bottlerocket/host-containers/admin/`.

All host containers come with persistent storage at `/.bottlerocket/host-containers/$HOST_CONTAINER_NAME` that is persisted across reboots and container start/stop cycles.

**Comment by chathsuom** [comment]
We are using google authenticator. Need to preserve data across instance rotations to avoid user re-registration

**Comment by chathsuom** [comment]
Manage to do a workaround. 
```
mkdir -p /.bottlerocket/host-containers/admin/home
mount <efs_id>.efs.region.amazonaws.com:/home /.bottlerocket/host-containers/admin/home
useradd -b /.bottlerocket/host-containers/admin/home -m -G users "$SaveUserName"
```

**Comment by etungsten** [comment]
Glad to hear you have a workaround. I'm gonna go ahead and close the issue. Please re-open if you think the workaround is insufficient.
