### ISSUE TITLE
Support using keys from IMDS as TrustedUserCAKeys

### ISSUE THREAD

**Issue by backjo** [bottlerocket-os/bottlerocket-admin-container#17]
**Image I'm using:**
Latest (v0.5.2)

**Issue or Feature Request:**
Feature Request!

Today, we're using a custom BottleRocket admin container to achieve certificate-based authentication for SSH users - this issue is mainly to determine whether this change would be welcome upstream. 

We're adding the following line to our sshd_config:
```
TrustedUserCAKeys /home/ec2-user/.ssh/authorized_keys
```

This allows us to upload the public part of our signing key(s) into AWS, and then manage SSH access through issuance of signed certificates. I think the main downside into enabling this is that there might be folks who for some reason are using their SSH private keys today to also do signing with an 'ec2-user' principal - though that seems fairly unlikely.

**Comment by tjkirch** [comment]
Thanks for the suggestion!  @jahkeup said he's used this as well, and had to specify both `TrustedUserCAKeys` and `AuthorizedKeysFile` to make sure both options are still effective.  I'm curious whether you can point them at the same file, and the format that matches will take effect?

**Comment by backjo** [comment]
@tjkirch it turns out you can! I tested out the changes in #18 , and was able to authenticate with an authorized key, as well as a CA-signed key

**Comment by jpculp** [comment]
@backjo, I just wanted to follow-up that we included the ability to specify `TrustedUserCAKeys` with the change to the admin container logic to use public keys from user-data (#19). This feature is available as of [v0.6.0](https://github.com/bottlerocket-os/bottlerocket-admin-container/releases/tag/v0.6.0) and included in [Bottlerocket v1.0.6](https://github.com/bottlerocket-os/bottlerocket/releases/tag/v1.0.6)! I encourage you to check out the example in the [authenticating with the admin container](https://github.com/bottlerocket-os/bottlerocket-admin-container/#authenticating-with-the-admin-container) documentation. Thank you again for the suggestion!

**Comment by backjo** [comment]
hey @jpculp  - thanks for pinging! We've actually been on 1.0.7 and using this for a while - works great!
