### ISSUE TITLE
Use a different username than `ec2-user`

### ISSUE THREAD

**Issue by zmrow** [bottlerocket-os/bottlerocket-admin-container#31]
**Image I'm using:**
v0.7.0

**Issue or Feature Request:**
When running Bottlerocket outside of EC2 it's odd to login to the admin container with `ec2-user@...`.

We could use a generic user name instead, something like `admin-user`.  The change may be jarring for folks currently running on EC2, so potentially we could have both for a short time?

**Comment by jpculp** [comment]
Merged code to specify user in host-container user-data.
