### ISSUE TITLE
sheltie error: "nsenter: reassociate to namespace 'ns/cgroup' failed: Operation not permitted"

### ISSUE THREAD

**Issue by alicancakil** [bottlerocket-os/bottlerocket-admin-container#57]
Hello, I am new to Bottlerocket 👋 🔰 

I am unable to use `sheltie` to get access to a root shell in the bottlerocket's root file system.

I get `nsenter: reassociate to namespace 'ns/cgroup' failed: Operation not permitted` error

**Image I'm using:**

- AMI: `ami-0f19ffae2329a1b41`
- Version: `bottlerocket-aws-k8s-1.21-x86_64-v1.7.0-bf3ca665`

**Steps to reproduce:**

1. Use `SSM` to start a session with bottlerocket host
2. run `enter-admin-container` to get access to the admin container
3. type `sudo sheltie`

Result: `nsenter: reassociate to namespace 'ns/cgroup' failed: Operation not permitted`

I would love to know if I am missing something here or if this is a bug.
Thank you kindly

**Comment by jpculp** [comment]
Hi @alicancakil, thanks for reaching out and welcome to Bottlerocket 🚀

Are you making any customizations via your userdata? I was unable to replicate the issue above with `ami-0f19ffae2329a1b41` (ca-central-1).

**Comment by alicancakil** [comment]
Hello @jpculp 
Thanks for your response. 

You are right. I made customizations with user data and `superpowered` was set to `false`

Changing it to this solved the problem;


```
[settings.host-containers.admin]
superpowered = true
```
