### ISSUE TITLE
sheltie hard-codes the rootfs location

### ISSUE THREAD

**Issue by samuelkarp** [bottlerocket-os/bottlerocket-admin-container#7]
[This line](https://github.com/bottlerocket-os/bottlerocket-admin-container/blob/f969cba3b0ff4f5da7d2bcc85101e7abe5ff6793/sheltie#L12) is a hard-coded reference to the location of the container's root filesystem relative to the host's root filesystem.  This is tightly coupled with the directory that we picked for storing containerd data ("/run/host-containerd"), the directory layout chosen by containerd for its data, and the name "admin".  Attempting to run sheltie from a container named anything different or from a differently-configured containerd will produce unexpected results.

**Comment by bcressey** [comment]
See https://github.com/bottlerocket-os/bottlerocket/issues/325 for the host side of this.
