### ISSUE TITLE
Feature Request: Add settings for SSHD MACs

### ISSUE THREAD

**Issue by mlacko64** [bottlerocket-os/bottlerocket-admin-container#90]
**Issue or Feature Request:**

Good day,
Is it possible to add support for setting MACs in sshd config? Currently ciphers and key-exchange-algorithms can be changed, but our vulnerability scanner is also reporting that there are used deprecated MACs, which we cannot change now in admin container.

Thank you very much

**Comment by mlacko64** [comment]
Created a pull request https://github.com/bottlerocket-os/bottlerocket-admin-container/pull/91 with code change

**Comment by markusboehme** [comment]
Hi @mlacko64, thanks again for your PR! The feature has been released with admin container version v0.11.3 as used in Bottlerocket v1.18.0 and later.
